### ISSUE TITLE
trinket issues

### ISSUE THREAD

**Issue by cooked71** [maffeen/wip-device_xiaomi_laurel_sprout-twrp#1]
hi, i've followed your guide to compile (for learning purpose) but I was not able to go thru I've this issue

ninja: error: '/home/cooked/twrp_by_maffen/out/target/product/laurel_sprout/obj/STATIC_LIBRARIES/bootctrl.trinket_intermediates/export_includes', needed by '/home/cooked/twrp_by_maffen/out/target/product/laurel_sprout/obj/EXECUTABLES/update_engine_sideload_intermediates/import_includes', missing and no known rule to make it
15:15:53 ninja failed with: exit status 1

Thanks

**Comment by maffeen** [comment]
Hi.
Sorry, but at the moment this device tree is kinda broken (missing init script or whatever).
Cloning hardware/qcom/bootctrl from Lineage should fix your error.

**Comment by maffeen** [comment]
https://github.com/LineageOS/android_hardware_qcom_bootctrl You can find it here.

**Comment by cooked71** [comment]
thanks for your fast support,
